version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: go_asset-postgres
    restart: always
    environment:
      POSTGRES_DB: go_asset_db
      POSTGRES_USER: local
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      - PGADMIN_DEFAULT_EMAIL=aryansinghyadav@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 80:80
    depends_on:
      - postgres
    
volumes:
  pgdata: